### ISSUE TITLE
adding the static sample data to the webpage

### ISSUE THREAD

**Issue by velazqje** [alclary/CS_340_Group#2]

**Comment by velazqje** [comment]
currently have the first 5 sample data for all tables except MovieGenres hardcoded

issues with what's there..
some of the samples have like a customer that's a number 6+ that I did not hardcode... so it doesn't add up 100% right now

haven't added anything into MovieGenres yet

**Comment by alclary** [comment]
Done; dummy data is all up 78c55a6
