### ISSUE TITLE
Data Manipulation Query file....

### ISSUE THREAD

**Issue by velazqje** [alclary/CS_340_Group#4]
**GENERALLLL - WOULD WE NEED TO  FIGURE OUT WHICH WOULD MAKE SENSE TO DELETE, UPDATE, CREATE....**

CUSTOMER TABLE - 
**CREATE RETRIEVE UPDATE DELETE**
* ALL FOUR

MOVIE TABLE -
 **CREATE RETRIEVE UPDATE** 
* DON'T SEE A NEED FOR DELETE ??????? 

THEATER TABLE -
 **RETRIEVE**
* INITIAL THOUGHTS ARE THAT WE DON'T NEED TO DELETE..... UNLESS WE "CLOSE" SAID THEATER...
*  SAME THING WITH CREATING... OUT OF SCOPE FOR THIS PROJECT I WOULD SAY
* UPDATE SAME THING..
 
GENRE TABLE - 
**RETRIEVE**
* SIMILAR TO THEATER TABLE I DON'T SEE WHY WE WOULD DELETE
* I DON'T SEE A NEED TO UPDATE
* ADD???

SHOWTIME TABLE - 
**CREATE RETRIEVE UPDATE DELETE**
* ALL FOUR

TICKET TABLE - 
**CREATE RETRIEVE UPDATE**
* DELETE????  NOT SURE

MOVIE GENRE

**Comment by alclary** [comment]
3760910
